controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_commande_ajouter_produit:
  path: /panier/ajouter/{id}
  controller: App\Controller\CommandeController::ajouterProduitAuPanier
